"""Pydantic schemas for LLM structured communication."""

from pydantic import BaseModel, Field


class JobRequirements(BaseModel):
    """Structured job requirements extracted by the JDAnalystAgent."""

    required_skills: list[str] = Field(
        ..., description="List of strictly required skills from the job description."
    )
    preferred_skills: list[str] = Field(
        default_factory=list, description="List of preferred or 'nice-to-have' skills."
    )
    seniority: str = Field(
        ..., description="The seniority level, e.g., 'Junior', 'Mid', 'Senior'."
    )
    experience_band_min: float = Field(
        ..., description="Minimum years of experience required."
    )
    experience_band_max: float | None = Field(
        None, description="Maximum years of experience, if explicitly stated."
    )
    core_responsibilities: list[str] = Field(
        default_factory=list, description="Top 3 to 5 core responsibilities."
    )


class EvidencePackage(BaseModel):
    """Compact package of candidate data sent to the RecruiterAgent."""

    candidate_id: str
    semantic_match_score: float
    behaviour_score: float
    canonical_title: str
    experience_years: float
    canonical_skills: list[str]
    resume_extract: str
    data_quality_warning: str | None = None


class RecruiterEvaluation(BaseModel):
    """Evaluation generated by the RecruiterAgent."""

    candidate_id: str = Field(...)
    fit_score: float = Field(
        ..., ge=0.0, le=100.0, description="Score from 0-100 indicating fit."
    )
    strengths: list[str] = Field(
        ..., description="Top reasons why the candidate is a good fit."
    )
    gaps: list[str] = Field(
        ..., description="Key missing requirements or areas of concern."
    )
    reasoning: str = Field(
        ..., description="A concise, 2-3 sentence justification for the fit_score."
    )


class CriticReview(BaseModel):
    """Review and potential score adjustment generated by the CriticAgent."""

    candidate_id: str = Field(...)
    original_fit_score: float = Field(...)
    adjusted_fit_score: float = Field(
        ..., ge=0.0, le=100.0, description="The final fit score after critic review."
    )
    adjustment_reasoning: str = Field(
        ..., description="Explanation of why the score was maintained or adjusted."
    )
    is_hallucination_detected: bool = Field(
        ..., description="True if the recruiter hallucinated facts not in evidence."
    )
